### PR TITLE
Schemas publication and version refactoring

### PR DESCRIPTION
**Pull request by sbesson**
This contains two complementary changes

- 91de3a6b1163eb0f3a054bf5c1079df73cfd3c23 refactors the publication of the BikeShed generated content, removing the need to duplicate actions and using for loops. Ideally, publishing a new version should solely require the addition of an item  to the `versions` array
- 0c0715af314f16993db84746387cdbacd2e70a71 add support for publishing the JSON schemas. A new `schemas` lists all existing schemas (currently `image.schema` and `strict_image.schema`). Each schema is copied under `<version>/schemas` if it exists in the source

### CODE REVIEW

**Comment by sbesson** [comment]
Last commit is consumed in https://github.com/sbesson/ngff/commit/20e74c26b71496ac2bbda4acd1bcafef7d85a1b4  - see https://github.com/sbesson/ngff/runs/6008683630?check_suite_focus=true for the GH Actions, https://github.com/sbesson/ngff/tree/gh-pages for the generated pages and https://sbesson.github.io/ngff/ for the GH pages deployment (esp. https://sbesson.github.io/ngff/0.4/schemas/image.schema)

**Comment by joshmoore** [comment]
Happy to give it a try. We'll still have to work on the `glob` though :smile:

**Comment by sbesson** [comment]
> We'll still have to work on the glob though 😄

Something along these lines would be ideal. Two quick comments:

- I think I originally tried to just copy the content `<version>/schemas` but failed to get the build working after spending a lot of time battling with the action. Possibly someone with more language experience might want to get involved
- https://github.com/ome/ngff/tree/main/0.3/schemas contains more than the JSON schemas. This PR goes for the conservative approach of only exposing the schemas we would consider for production. Maybe as we start introducing additional schemas, we will want to define rules/clean up old versions and add the logic to discover and publish schemas

**Review by joshmoore — APPROVED** [review]
:+1:

**Comment by sbesson** [comment]
What's your take-on on the tags management - https://github.com/ome/spec-prod/tags ? are we maintaining a coupling between OME-NGFF spec versions and tags of this action and updated `v4` or is that `v5`?

**Comment by joshmoore** [comment]
Happy to remove the previous versions. Preferably we should post-fix.

For what it's worth, upstream is now at v2.7.1!

**Comment by sbesson** [comment]
:+1: for removing the versions as they create confusion with the upstream tags. For the reference, I'd be tempted to use commit SHA1 to be explicit unless you think we should use `@main`?

**Comment by joshmoore** [comment]
We could try main for a while to reduce the noise. I assume there won't be too many moving parts initially.

**Pull request merged**
