### PR TITLE
Add HCS schemas to the GH pages publication script

### PR DESCRIPTION
**Pull request by sbesson**
See https://github.com/ome/ome-zarr-py/pull/142#issuecomment-1174434046

### CODE REVIEW

**Comment by will-moore** [comment]
Changes look good. I'm assuming that the schemas aren't actually deployed to https://ngff.openmicroscopy.org/0.4/schemas/plate.schema and https://ngff.openmicroscopy.org/0.4/schemas/well.schema until after this is merged?

**Comment by sbesson** [comment]
That's correct. Ideally this could be replaced by wilcard to copy everything under `/schemas` for each version but my attempts have failed so that's the easiest way to publish things

**Review by will-moore — APPROVED** [review]
OK, LGTM 👍

**Comment by sbesson** [comment]
Re-executed https://github.com/ome/ngff/actions/runs/2611161053 which in turn updated the GitHub Pages. The schemas should now be available live

**Comment by joshmoore** [comment]
:+1: We probably need to document all the steps for adding a schema somewhere.

**Comment by sbesson** [comment]
Agreed. Thoughts about https://github.com/ome/ngff#release-process or a separate section?

**Comment by joshmoore** [comment]
Starting there probably makes sense. Eventually, I'd imagine a how to as part of the spec itself concerning the process, etc. But that needs a good deal of drafting.

**Pull request merged**
